Move weston-egl-ext.h include to gles2-renderer.c
The weston-egl-ext.h include in compositor.h is not needed.  Rather,
it is only needed by gles2-renderer.c.  This also fixes external
module compile error since weston-egl-ext.h is not part of the
Weston SDK:

weston/compositor.h:39:28: fatal error: weston-egl-ext.h:
	No such file or directory

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>